name: Build Chips

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build All Chips
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install wokwi-cli
        run: npm install -g wokwi-cli

      - name: Build all chips
        run: ./build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chips
          path: |
            dist/*.wasm
            dist/*.json

  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled chips
        uses: actions/download-artifact@v4
        with:
          name: chips
          path: dist

      - name: Create a zip archive
        working-directory: dist
        run: zip -r ../chips.zip .

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: chips.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
