name: Build Chip

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-a3144:
    name: Build A3144
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build a3144 chip
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: "a3144/chip.c"
          output-name: "a3144.chip.wasm"

      - name: Copy a3144 chip.json
        run: |
          mkdir -p dist
          cp a3144/chip.json dist/a3144.chip.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: a3144-chip
          path: |
            dist/a3144.chip.json
            dist/a3144.chip.wasm

  # The release job only runs when you push a tag starting with "v", e.g. v1.0.0
  release:
    name: Release
    needs: build-a3144
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled chip
        uses: actions/download-artifact@v4
        with:
          name: a3144-chip
          path: chip

      - name: Create a zip archive
        run: cd chip && zip -9 ../chip.zip a3144.*
        env:
          ZIP_VERSION: ${{ github.ref_name }}

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: chip.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
